### ISSUE TITLE
Support building with system flatbuffers

### ISSUE THREAD

**Issue by SuperSandro2000** [hyperion-project/hyperion-obs-plugin#7]
Currently external/flatbuffers must be used to build and there is no option to build it with a distro flatbuffers.

**Comment by Paulchen-Panther** [comment]
@SuperSandro2000 
I included the feature in PR #9 and it is now in the master.
CMake position: https://github.com/hyperion-project/hyperion-obs-plugin/blob/main/CMakeLists.txt#L32

Greetings Paulchen
